[package]
name = "sha-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.3"
egui = "0.20.1"
eframe = "0.20.1"
native-dialog = "0.6.3"
egui_file = "0.5.4"